#!/usr/bin/env python3

import json
import os
import subprocess
import sys
from pathlib import Path


if len(sys.argv) != 3:
    print(
        f"Usage: {sys.argv[0]} SMALLOC_REPO WORKSPACE",
        file=sys.stderr,
    )
    raise SystemExit(2)


smalloc_repo = Path(sys.argv[1]).resolve()
workspace = Path(sys.argv[2]).resolve()

config_dir = workspace / ".cargo"
config_file = config_dir / "config.toml"
metadata_file = workspace / "allocator-metadata.txt"
pins_file = workspace / "allocator-pins.tsv"

required_packages = {
    "smmalloc",
    "tikv-jemallocator",
    "mimalloc",
    "snmalloc-rs",
    "rpmalloc",
}

allocator_fragments = (
    "jemalloc",
    "mimalloc",
    "snmalloc",
    "rpmalloc",
)


def command_output(arguments, cwd=None):
    return subprocess.check_output(
        arguments,
        cwd=cwd,
        text=True,
    )


def source_tree_b3(directory):
    directory = Path(directory)
    process = subprocess.Popen(
        ["b3sum", "--no-names"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        text=False,
    )

    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue

        relative = path.relative_to(directory).as_posix()

        if relative.startswith(".git/") or relative.startswith("target/"):
            continue

        encoded = relative.encode()
        process.stdin.write(len(encoded).to_bytes(8, "little"))
        process.stdin.write(encoded)

        with path.open("rb") as file:
            while block := file.read(1024 * 1024):
                process.stdin.write(block)

    process.stdin.close()
    digest = process.stdout.read().decode().strip()
    return_code = process.wait()

    if return_code != 0:
        raise SystemExit(return_code)

    return digest


# Do not let a patch configuration generated by a previous run affect
# resolution of this run's canonical Cargo.lock.
if config_file.exists():
    config_file.unlink()

metadata_json = command_output(
    [
        "cargo",
        "metadata",
        "--locked",
        "--format-version=1",
        "--all-features",
    ],
    cwd=smalloc_repo,
)

cargo_metadata = json.loads(metadata_json)

selected = []

for package in cargo_metadata["packages"]:
    name = package["name"].lower()

    if (
        package["name"] in required_packages
        or any(fragment in name for fragment in allocator_fragments)
    ):
        selected.append(package)

found_required = {package["name"] for package in selected}
missing = sorted(required_packages - found_required)

if missing:
    raise SystemExit(
        "canonical smalloc dependency graph is missing: "
        + ", ".join(missing)
    )

selected.sort(key=lambda package: package["name"])

config_dir.mkdir(parents=True, exist_ok=True)

with config_file.open("w") as file:
    file.write("# Generated by tools/prepare-allocator-pins.py\n")
    file.write("[patch.crates-io]\n")

    for package in selected:
        package_name = package["name"]
        package_dir = Path(package["manifest_path"]).parent
        escaped_path = str(package_dir).replace("\\", "\\\\").replace('"', '\\"')

        file.write(
            f'"{package_name}" = {{ path = "{escaped_path}" }}\n'
        )

with pins_file.open("w") as file:
    for package in selected:
        package_dir = Path(package["manifest_path"]).parent

        file.write(
            f"{package['name']}\t"
            f"{package['version']}\t"
            f"{package['manifest_path']}\n"
        )

lockfile = smalloc_repo / "Cargo.lock"
lockfile_hash = command_output(
    ["b3sum", "--no-names", str(lockfile)]
).strip()

config_hash = command_output(
    ["b3sum", "--no-names", str(config_file)]
).strip()

with metadata_file.open("w") as file:
    file.write("Allocator source metadata\n")
    file.write("=========================\n")
    file.write(f"canonical Cargo.lock: {lockfile}\n")
    file.write(f"canonical Cargo.lock BLAKE3: {lockfile_hash}\n")
    file.write(f"Cargo patch config BLAKE3: {config_hash}\n")
    file.write(f"rustc: {command_output(['rustc', '--version']).strip()}\n")
    file.write(f"cargo: {command_output(['cargo', '--version']).strip()}\n")

    try:
        clang = command_output(["clang++", "--version"]).splitlines()[0]
        file.write(f"C++ compiler: {clang}\n")
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    for package in selected:
        package_dir = Path(package["manifest_path"]).parent
        source_hash = source_tree_b3(package_dir)

        file.write("\n")
        file.write(f"package: {package['name']}\n")
        file.write(f"version: {package['version']}\n")
        file.write(f"source: {package.get('source') or 'local path'}\n")
        file.write(f"manifest: {package['manifest_path']}\n")
        file.write(f"source-tree BLAKE3: {source_hash}\n")

        vcs_file = package_dir / ".cargo_vcs_info.json"

        if vcs_file.exists():
            vcs = json.loads(vcs_file.read_text())
            sha1 = vcs.get("git", {}).get("sha1")

            if sha1:
                file.write(f"crate publication git commit: {sha1}\n")

print(f"Generated {config_file}")
print(f"Generated {pins_file}")
print(f"Generated {metadata_file}")
